### PR TITLE
Convert to mysqli

### PR DESCRIPTION
**Pull request by nicjansma**
This is a partial fix for https://github.com/sergeychernyshev/showslow/issues/116.

I'm currently in the middle of a server migration, and for some reason decided to give PHP 7 a try.

Since the `mysql` extension has been [deprecated / removed](https://wiki.php.net/rfc/remove_deprecated_functionality_in_php7), Show Slow needed an upgrade to `mysqli`.

It's somewhat straightforward of a migration.  For example, you can follow [this guide](https://www.phpclasses.org/blog/package/9199/post/3-Smoothly-Migrate-your-PHP-Code-using-the-Old-MySQL-extension-to-MySQLi.html).

With these changes I'm able to click around most screens in the UI without any issue, though I honestly have not done extensive testing.

~Note I see some additional errors in `users` when trying to log in (and I keep getting the login screen).~

### CODE REVIEW

**Comment by nicjansma** [comment]
Ah!  I see that `users` has already been updated.

**Comment by sergeychernyshev** [comment]
Nic, thank you for giving it a go!

Yeah, old mysql default values for timestamp fields, I just fixed them the other day.

You say you did a partial fix - what do you think is not done?

**Comment by nicjansma** [comment]
I originally thought it wasn't complete because my cached version of `users` still had some `mysql` references, but it looks like that's fixed already.

So as far as I can tell, all of the old `mysql_` references in this repo have been fixed... but I just haven't had the chance to fully test all of the functionality other than clicking around the dashboard.

**Comment by sergeychernyshev** [comment]
Yeah, Startup API (/users/) always used MySQLi, but had some mysql table upgrade issues (stuff gets deprecated in MySQL in non-backwards compatible way).

Should be fixed - basically, only way to stay in sync for ShowSlow is to run make which will grab latest subpackages and apply all the hacks/fixes to database.

**Comment by nicjansma** [comment]
Sounds like a plan -- haven't found any additional problems with a little more testing today.

**Comment by sergeychernyshev** [comment]
OK, those few beacons that I was able to make (or fake) seem to work so I assume it is all good.
I'll try switching to it in public instance and testing there.

**Comment by sergeychernyshev** [comment]
OK, seems to work fine in general - would require testing all beacons to make sure it's still true, but YSlow beacon that runs on public instance and HAR beacon that I tested seem to work.

**Pull request merged**
